altemoi/altemoi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('terminal/', include('terminal.urls', namespace = "terminal")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

altemoi/terminal/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.decorators import login_required

from . import views
app_name = "terminal"

urlpatterns = [
                path('tablon', login_required(views.Tablon), name='tablon'),

                path('nuevaterminal', login_required(views.NuevaTerminal.as_view()), name='nueva_lvidaqa'),
                path('listaterminal', login_required(views.ListaTerminal.as_view()), name='lista_lvidaqa'),
                re_path(r'^editarterminal/(?P<pk>\d+)/$', login_required(views.EditarTerminal.as_view()), name='editar_lvidaqa'),
                re_path(r'^eliminarterminal/(?P<pk>\d+)/$', login_required(views.EliminarTerminal.as_view()), name='eliminar_lvidaqa'),


                path('nuevapuerta', login_required(views.NuevaPuerta.as_view()), name='nueva_lasom'),
                path('listapuerta', login_required(views.ListaPuerta.as_view()), name='lista_lasom'),
                re_path(r'^editarpuerta/(?P<pk>\d+)/$', login_required(views.EditarPuerta.as_view()), name='editar_lasom'),
                re_path(r'^eliminarpuerta/(?P<pk>\d+)/$', login_required(views.EliminarPuerta.as_view()), name='eliminar_lasom'),


                path('nuevaplataforma', login_required(views.NuevaPlataforma.as_view()), name='nueva_lmala'),
                path('listaplataforma', login_required(views.ListaPlataforma.as_view()), name='lista_lmala'),
                re_path(r'^editarplataforma/(?P<pk>\d+)/$', login_required(views.EditarPlataforma.as_view()), name='editar_lmala'),
                re_path(r'^eliminarplataforma/(?P<pk>\d+)/$', login_required(views.EliminarPlataforma.as_view()), name='eliminar_lmala'),


                path('nuevaboleteria', login_required(views.NuevaBoleteria.as_view()), name='nueva_nmen'),
                path('listaboleteria', login_required(views.ListaBoleteria.as_view()), name='lista_nmen'),
                re_path(r'^editarboleteria/(?P<pk>\d+)/$', login_required(views.EditarBoleteria.as_view()), name='editar_nmen'),
                re_path(r'^eliminarboleteria/(?P<pk>\d+)/$', login_required(views.ElimininarBoleteria.as_view()), name='eliminar_nmen'), #falta implementar esto




]

altemoi/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">

    <!-- Cargo CSS de BS local -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <title> {% block title %}Altemoi{% endblock %}</title>


  </head>
  <body>
    <div class="container-fluid">

      {% block encabezado %}


        <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
          <a class="navbar-brand" href="#">Altemoi</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'terminal:tablon' %}">Inicio <span class="sr-only">Inicio</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'terminal:lista_lvidaqa' %}">Terminales</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'terminal:lista_lasom' %}">Puertas de embarque</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'terminal:lista_lmala' %}">Plataformas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'terminal:lista_nmen' %}">Boleterías</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sistema
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                </div>
              </li>
            </ul>
          </div>
        </nav>

      {% endblock %}

      {% block contenido %}

      {% endblock %}


      {% block pie %}
      <footer>
        <p>Altemoi</p>
      </footer>
      {% endblock %}

    </div>

    <!--Scripts de JQuery, Popper y BS -->
    <script src="{% static 'bootstrap/js/jquery-3.4.1.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'altemoiscripts/viewsupdates.js' %}"></script>

  </body>
</html>

altemoi/templates/base/selector_lvidaqa.html
{% extends 'base/base.html' %}

{% if object_list %}
  {% for terminal in object_list %}
    