altemoi/altemoi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('terminal/', include('terminal.urls', namespace = "terminal")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

altemoi/terminal/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.decorators import login_required

from . import views
app_name = "terminal"

urlpatterns = [
                path('tablon', login_required(views.Tablon), name='tablon'),

                path('nuevaterminal', login_required(views.NuevaTerminal.as_view()), name='nueva_lvidaqa'),
                path('listaterminal', login_required(views.ListaTerminal.as_view()), name='lista_lvidaqa'),
                re_path(r'^editarterminal/(?P<pk>\d+)/$', login_required(views.EditarTerminal.as_view()), name='editar_lvidaqa'),
                re_path(r'^eliminarterminal/(?P<pk>\d+)/$', login_required(views.EliminarTerminal.as_view()), name='eliminar_lvidaqa'),


                path('nuevapuerta', login_required(views.NuevaPuerta.as_view()), name='nueva_lasom'),
                path('listapuerta', login_required(views.ListaPuerta.as_view()), name='lista_lasom'),
                re_path(r'^editarpuerta/(?P<pk>\d+)/$', login_required(views.EditarPuerta.as_view()), name='editar_lasom'),
                re_path(r'^eliminarpuerta/(?P<pk>\d+)/$', login_required(views.EliminarPuerta.as_view()), name='eliminar_lasom'),


                path('nuevaplataforma', login_required(views.NuevaPlataforma.as_view()), name='nueva_lmala'),
                path('listaplataforma', login_required(views.ListaPlataforma.as_view()), name='lista_lmala'),
                re_path(r'^editarplataforma/(?P<pk>\d+)/$', login_required(views.EditarPlataforma.as_view()), name='editar_lmala'),
                re_path(r'^eliminarplataforma/(?P<pk>\d+)/$', login_required(views.EliminarPlataforma.as_view()), name='eliminar_lmala'),


                path('nuevaboleteria', login_required(views.NuevaBoleteria.as_view()), name='nueva_nmen'),
                path('listaboleteria', login_required(views.ListaBoleteria.as_view()), name='lista_nmen'),
                re_path(r'^editarboleteria/(?P<pk>\d+)/$', login_required(views.EditarBoleteria.as_view()), name='editar_nmen'),
                re_path(r'^eliminarboleteria/(?P<pk>\d+)/$', login_required(views.ElimininarBoleteria.as_view()), name='eliminar_nmen'), #falta implementar esto




]

altemoi/templates/lvidaqa/nachaxan/lasom.html
    <div class="row">
    	<div class="col-md-2">
    		<h5>Puertas de embarque</h5>
    		<hr>
    		<div class="card card-body">
          {% if puertas %}
    			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'terminal:nueva_lasom' %}">Crear puerta de embarque</a>
          {% else %}
          <a class="btn btn-danger  btn-sm btn-block" href="{% url 'terminal:nueva_lasom' %}">Crear puerta de embarque</a>
          {% endif %}
    			<table class="table table-sm">
    				<tr>
    					<th>Identificación</th>
              <th>Acciones</th>
    				</tr>
            <tbody>
              <!-- Veo si hay registros de terminales para mostrar-->

                {% for puerta in puertas %}
                  <tr>
                    <td>{{puerta.denominacion}}</td>
                    <td>
                      <div class="dropdown">
                       <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                         Acciones
                       </button>
                       <div class="dropdown-menu">
                           <a class="dropdown-item" href="{% url 'terminal:editar_lasom' puerta.id %}">Editar</a>
                           <a class="dropdown-item" href="{% url 'terminal:eliminar_lasom' puerta.id %}">Eliminar</a>
                       </div>
                     </div>
                    </td>
                  </tr>
                {% endfor %}

            </tbody>
    			</table>
    		</div>
    	</div>

altemoi/templates/lvidaqa/nachaxan/lmala.html
    <!-- Tabla de Plataformas que se muestra en tablón -->

    <div class="col-md-3" id="miniLmala">
      <h5>Plataformas</h5>
      <hr>
      <div class="card card-body">
        <a class="btn btn-primary  btn-sm btn-block" href="{% url 'terminal:nueva_lmala' %}">Crear plataforma</a>
        <table class="table table-sm">
          <tr>
            <th>Plataforma</th>
            <th>Puerta de embarque</th>
            <th>Acciones</th>
          </tr>
          <tbody>

            {% for plataforma in plataformas %}
              <tr>
                <td>{{plataforma.numeroID}}</td>
                <td>{{plataforma.puertaembarque.denominacion}}</td>
                <td>
                  <div class="dropdown">
                   <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                     Acciones
                   </button>
                   <div class="dropdown-menu">
                       <a class="dropdown-item" href="{% url 'terminal:editar_lmala' plataforma.id %}">Editar</a>
                       <a class="dropdown-item" href="{% url 'terminal:eliminar_lmala' plataforma.id %}">Eliminar</a>
                   </div>
                 </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
    </div>

altemoi/templates/lvidaqa/nachaxan/lvidaqa.html
<!-- Veo si hay registros de terminales para mostrar-->

<table id="listadoTerminal" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Denominación</td>
      <td>Domicilio</td>
      <td>Teléfono</td>
      <td>Correo electrónico</td>
      <td>ID Impositivo</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>




  {% for terminal in terminales %}
    <tr>
      <td>{{terminal.id}}</td>
      <td>{{terminal.denominacion}}</td>
      <td>{{terminal.domicilio}}</td>
      <td>{{terminal.telefono}}</td>
      <td>{{terminal.email}}</td>
      <td>{{terminal.nro_impositivo}}</td>
        <!-- Botonera -->

        <td>
        	<div class="dropdown">
        		<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        		 Acciones
        		</button>
        		<div class="dropdown-menu">
        				<a class="dropdown-item" href="{% url 'terminal:editar_lvidaqa' terminal.id %}">Editar</a>
        				<a class="dropdown-item" href="{% url 'terminal:eliminar_lvidaqa' terminal.id %}">Eliminar</a>
        		</div>

        </div>
        </td>

    </tr>
  {% endfor %}

</tbody>
</table>

altemoi/templates/lvidaqa/nachaxan/nmen.html
    <div class="col-md-7">
      <h5>Boleterías</h5>
      <hr>
      <div class="card card-body">
        {% if boleterias %}
          <a class="btn btn-primary  btn-sm btn-block" href="{% url 'terminal:nueva_nmen' %}">Crear boletería</a>
        {% else %}
          <a class="btn btn-danger  btn-sm btn-block" href="{% url 'terminal:nueva_nmen' %}">Crear boletería</a>
        {% endif %}
        <table class="table table-sm">
          <tr>
            <td>Terminal</td>
            <td>Identificador</td>
            <td>Teléfono público</td>
            <td>Interno</td>
            <td>Correo electrónico</td>
            <td>Persona contacto</td>
            <td>Teléfono urgencia</td>
            <td>Estado</td>
          </tr>
          <tbody>

            {% for boleteria in boleterias %}

              <tr>
                <td>{{boleteria.terminal.denominacion}}</td>
                <td>{{boleteria.numeroID}}</td>
                <td>{{boleteria.telefono}}</td>
                <td>{{boleteria.internoTelefono}}</td>
                <td>{{boleteria.email}}</td>
                <td>{{boleteria.nombreContacto}}</td>
                <td>{{boleteria.telefonoEmergencia}}</td>
                <td>{{boleteria.status.denominacion}}</td>
                <td>
                  <div class="dropdown">
                   <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                     Acciones
                   </button>
                   <div class="dropdown-menu">
                       <a class="dropdown-item" href="{% url 'terminal:editar_nmen' boleteria.id %}">Editar</a>
                       <a class="dropdown-item" href="{% url 'terminal:eliminar_nmen' boleteria.id %}">Eliminar</a>
                   </div>

                </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
    </div>