altemoi/altemoi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('terminal/', include('terminal.urls', namespace = "terminal")),
    path('usuarios/', include('usuarios.urls', namespace= "usuarios")),
    path('', LoginView.as_view(template_name='index.html'), name = "login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),
]

altemoi/terminal/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.decorators import login_required

from . import views
app_name = "terminal"

urlpatterns = [
                path('tablon', login_required(views.Tablon), name='tablon'),

                path('nuevaterminal', login_required(views.NuevaTerminal.as_view()), name='nueva_lvidaqa'),
                path('listaterminal', login_required(views.ListaTerminal.as_view()), name='lista_lvidaqa'),
                re_path(r'^editarterminal/(?P<pk>\d+)/$', login_required(views.EditarTerminal.as_view()), name='editar_lvidaqa'),
                re_path(r'^eliminarterminal/(?P<pk>\d+)/$', login_required(views.EliminarTerminal.as_view()), name='eliminar_lvidaqa'),


                path('nuevapuerta', login_required(views.NuevaPuerta.as_view()), name='nueva_lasom'),
                path('listapuerta', login_required(views.ListaPuerta.as_view()), name='lista_lasom'),
                re_path(r'^editarpuerta/(?P<pk>\d+)/$', login_required(views.EditarPuerta.as_view()), name='editar_lasom'),
                re_path(r'^eliminarpuerta/(?P<pk>\d+)/$', login_required(views.EliminarPuerta.as_view()), name='eliminar_lasom'),


                path('nuevaplataforma', login_required(views.NuevaPlataforma.as_view()), name='nueva_lmala'),
                path('listaplataforma', login_required(views.ListaPlataforma.as_view()), name='lista_lmala'),
                re_path(r'^editarplataforma/(?P<pk>\d+)/$', login_required(views.EditarPlataforma.as_view()), name='editar_lmala'),
                re_path(r'^eliminarplataforma/(?P<pk>\d+)/$', login_required(views.EliminarPlataforma.as_view()), name='eliminar_lmala'),


                path('nuevaboleteria', login_required(views.NuevaBoleteria.as_view()), name='nueva_nmen'),
                path('listaboleteria', login_required(views.ListaBoleteria.as_view()), name='lista_nmen'),
                re_path(r'^editarboleteria/(?P<pk>\d+)/$', login_required(views.EditarBoleteria.as_view()), name='editar_nmen'),
                re_path(r'^eliminarboleteria/(?P<pk>\d+)/$', login_required(views.ElimininarBoleteria.as_view()), name='eliminar_nmen'), #falta implementar esto




]

altemoi/templates/lvidaqa/aqtaclasom.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar la puerta de embarque {{ object.denominacion }}?</h3>
  <button class= "btn btn-danger" type="submit" name="button">Eliminar</button>
  <a class= "btn btn-primary" href="{% url 'terminal:lista_lasom' %}">Cancelar</a>
</form>

{% endblock %}

altemoi/templates/lvidaqa/aqtaclmala.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar la plataforma ID {{ object.numeroID }}, denominación {{object.denominacion}}?</h3>
  <button class= "btn btn-danger" type="submit" name="button">Eliminar</button>
  <a class= "btn btn-primary" href="{% url 'terminal:lista_lmala' %}">Cancelar</a>
</form>

{% endblock %}

altemoi/templates/lvidaqa/aqtaclvidaqa.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar la terminal {{ object.denominacion }}?</h3>
  <button class= "btn btn-danger" type="submit" name="button">Eliminar</button>
  <a class= "btn btn-primary" href="{% url 'terminal:lista_lvidaqa' %}">Cancelar</a>
</form>

{% endblock %}

altemoi/templates/lvidaqa/aqtacnmen.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar la boletería {{ object.numeroID }}?</h3>
  <button class= "btn btn-danger" type="submit" name="button">Eliminar</button>
  <a class= "btn btn-primary" href="{% url 'terminal:lista_nmen' %}">Cancelar</a>
</form>

{% endblock %}

altemoi/templates/lvidaqa/iotlvidaqa.html
{% extends 'base/base.html'  %}

{% block contenido %}
<h3>Carga de estación terminal</h3>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-outline-success" name="button">Guardar estación</button>
</form>
{% endblock %}

altemoi/templates/lvidaqa/nachaxanlasom.html
{%  extends 'base/base.html' %}

{% block contenido %}

<table id="listadoPuertas" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Terminal</td>
      <td>Denominación/Número/Letra puerta de embarque</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de terminales para mostrar-->
    {% if object_list %}
      {% for puerta in object_list %}
        <tr>
          <td>{{puerta.id}}</td>
          <td>{{puerta.terminal.denominacion}}</td>
          <td>{{puerta.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'terminal:editar_lasom' puerta.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'terminal:eliminar_lasom' puerta.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay puertas de embarque registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'terminal:nueva_lasom' %}">Agregar puerta de embarque</a>
    {% endif %}
  </tbody>
</table>

{% endblock %}

altemoi/templates/lvidaqa/nachaxanlmala.html
{%  extends 'base/base.html' %}

{% block contenido %}

<table id="listadoPlataformas" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Terminal</td>
      <td>Identificador</td>
      <td>Denominación</td>
      <td>Puerta embarque</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de terminales para mostrar-->
    {% if object_list %}
      {% for plataforma in object_list %}
        <tr>
          <td>{{plataforma.id}}</td>
          <td>{{plataforma.terminal.denominacion}}</td>
          <td>{{plataforma.numeroID}}</td>
          <td>{{plataforma.denominacion}}</td>
          <td>{{plataforma.puertaembarque.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'terminal:editar_lmala' plataforma.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'terminal:eliminar_lmala' plataforma.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay plataformas registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'terminal:nueva_lmala' %}">Agregar plataforma</a>
    {% endif %}
  </tbody>
</table>

{% endblock %}

altemoi/templates/lvidaqa/nachaxanlvidaqa.html
{%  extends 'base/base.html' %}

{% block contenido %}

{% include 'lvidaqa/nachaxan/lvidaqa.html' %}

<div class="row">


	<div class="col">
		<div class="col-md">
			<div class="card text-center text-dark  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Arribos</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-dark  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Partidas</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-dark  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Arribos pendientes</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>
</div>

  {% include 'lvidaqa/nachaxan/lasom.html' %}

	{% include 'lvidaqa/nachaxan/lmala.html' %}

</div>
{% endblock contenido %}

altemoi/templates/lvidaqa/nachaxannmen.html
{%  extends 'base/base.html' %}

{% block contenido %}

<table id="listadoBoleterias" class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Terminal</td>
      <td>Identificador</td>
      <td>Teléfono público</td>
      <td>Interno</td>
      <td>Correo electrónico</td>
      <td>Persona contacto</td>
      <td>Teléfono urgencia</td>
      <td>Estado</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de boleterías para mostrar-->
    {% if object_list %}
      {% for boleteria in object_list %}
        <tr>
          <td>{{boleteria.id}}</td>
          <td>{{boleteria.terminal.denominacion}}</td>
          <td>{{boleteria.numeroID}}</td>
          <td>{{boleteria.telefono}}</td>
          <td>{{boleteria.internoTelefono}}</td>
          <td>{{boleteria.email}}</td>
          <td>{{boleteria.nombreContacto}}</td>
          <td>{{boleteria.telefonoEmergencia}}</td>
          <td>{{boleteria.status.denominacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
                 <a class="dropdown-item" href="{% url 'terminal:editar_nmen' boleteria.id %}">Editar</a>
                 <a class="dropdown-item" href="{% url 'terminal:eliminar_nmen' boleteria.id %}">Eliminar</a>
             </div>

          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay boleterías registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'terminal:nueva_nmen' %}">Agregar boletería</a>
    {% endif %}
  </tbody>
</table>

{% endblock %}